### ISSUE TITLE
Remove the offset comments in scenes/rooms

### ISSUE THREAD

**Issue by AngheloAlf** [NEstelami/ZAPD#111]
ZAPD is currently adding the offset as a comment some extracted arrays (See image).

This should be removed or changed to be a "debug feature", for example, passing a parameter like `--debug-offsets` when invoking ZAPD.

![imagen](https://user-images.githubusercontent.com/7416381/114201727-84c04e80-9924-11eb-9e63-36dcfa148090.png)

**Comment by AngheloAlf** [comment]
I'll work in this feature as part of the ZRoom refactor :D

**Comment by NEstelami** [comment]
I don't think ZAPD does this anymore?
