### ISSUE TITLE
Needs to add support to non-aligned textures

### ISSUE THREAD

**Issue by AngheloAlf** [NEstelami/ZAPD#125]
There are a few objects which have non double word aligned textures. These objects will not match with our current method (`u64` arrays for textures).

Full list of OoT objects with this problem:
- `object_oF1s`. Early goron. Unused.
- `object_kw1`. Red-Haired Kokiri Girl. Used in ending credits in Lon Lon Ranch.
- `object_cne`. Young Hylian Women.
- `object_bji`. Lon Lon credits and NPCs
- `object_ahg`. Hylian Men I. Lon Lon credits, uncursed HoS people, and NPCs
- `object_boj`. Hylian Men II. Happy Mask Shop Customer

MM needs to investigate if it has this problem too.

**Comment by EllipticEllipsis** [comment]
Testing shows that extracting these textures as `u32` instead allows them to align correctly and match.
