### ISSUE TITLE
ZAPD should support more object file types

### ISSUE THREAD

**Issue by Kenix3** [NEstelami/ZAPD#13]
Kenix
- [x] string
- [x] Vector (vec3s, vec3f, vec3i)
- [x] Primitive (u8/s8, u16/s16, u32/s32, u64/s64, f32, f64)

Jack

- [x] arrays
- [x] Standard skeletons
- [x] Flex skeletons
- [x] Standard limbs
- [x] LOD limbs
- [x] Skin limbs
- [x] Link animation headers
- [x] Legacy animation system (object_human)

**Comment by NEstelami** [comment]
Is `string` still something we want? Do we know of cases where it would be useful?

**Comment by AngheloAlf** [comment]
ZAPD already supports everything listed here. So I think this issue can be closed now.
