### ISSUE TITLE
ZAPD should support text decompilation to C files.

### ISSUE THREAD

**Issue by Kenix3** [NEstelami/ZAPD#14]
ZAPD should also support PAL and NTSC message systems.

**Comment by NEstelami** [comment]
We can probably backport `ZText` from ZAPDTR for this.

**Comment by louist103** [comment]
I have this started at:
https://github.com/louist103/ZAPD/tree/text

**Comment by Dragorn421** [comment]
This isn't required of ZAPD as far as the oot decomp is concerned, there's already different tooling in place to extract the text
And MM afaik the relevant code isn't (fully) decompiled yet?

**Comment by NEstelami** [comment]
I understand we have tooling in place for text extraction, but as I understand it's written in Python and currently takes around ten seconds to extract. I feel we can improve upon that extraction time, given Python isn't the best language for this kind of thing. If decomp doesn't want to use it that's fine but I still want the option to be available.

**Comment by Dragorn421** [comment]
For the record it takes ~1.5 seconds for me to extract both text files (regular and credits)
