### ISSUE TITLE
Allow to declare AnimatedTextures/Materials in XMLs

### ISSUE THREAD

**Issue by AngheloAlf** [NEstelami/ZAPD#143]
ZAPD currently is able to detect those in scenes, but they can't be declared in an XML file for objects.

One example is `object_death` at offsets `0xCB84` and `0xCBC0`.

**Comment by AngheloAlf** [comment]
I could work in this after #140 is merged, just to prevent conflicts.

**Comment by mzxrules** [comment]
what does it mean to be an animated texture?

**Comment by AngheloAlf** [comment]
I'm not completely sure tbh. It is a MM asset type, so you may want to ask them instead.
