### ISSUE TITLE
Change external assets' `#include`s to be consistent

### ISSUE THREAD

**Issue by AngheloAlf** [NEstelami/ZAPD#149]
Currently we have some assets that are being `#include`d with a `../` at the beginning of the path and other that doesn't have that.

Example:
```c
u16 object_bombiwa_TLUT_000000[] = {
    #include "assets/objects/object_bombiwa/tlut_00000000.rgb5a1.inc.c"
};

u8 object_bombiwa_Tex_000020[] = {
    #include "assets/objects/object_bombiwa/tex_00000020.ci4.inc.c"
};

static Vtx object_bombiwaVtx_000820[] = {
    #include "../assets/objects/object_bombiwa/object_bombiwaVtx_000820.vtx.inc"
};
```

Also, those `#include` should not be indented.

**Comment by cybergrunge-ops** [comment]
how do i compile vtx.inc and .c stuff into a more useable file format like obj or something or is there a program which i can use to modify the vtx.inc files

**Comment by mzxrules** [comment]
> how do i compile vtx.inc and .c stuff into a more useable file format like obj or something or is there a program which i can use to modify the vtx.inc files

This is not the place to ask for help

**Comment by cybergrunge-ops** [comment]
where should i ask this was the only search result on the entire internet for "vtx.inc file"

**Comment by Dragorn421** [comment]
We don't know what you are doing but this is not a help thread, and you are more than likely not using ZAPD (this repo). Try [StackOverflow](https://stackoverflow.com/) or some related site dedicated to asking questions
