### ISSUE TITLE
Externalize struct names

### ISSUE THREAD

**Issue by Dragorn421** [NEstelami/ZAPD#165]
It would be nice to have a configuration file for struct names used by ZAPD to write out assets in C, like `SkeletonHeader`, `CamData`, ...

This would make documentation easier by not having to first wait for ZAPD to be updated and merged into decomp repos

Edit: Following discussion on Discord about Jenkins difficulties this would bring, the idea would be:

Have `config.xml` with `<StructName id="FlexSkeletonHeader" name="MyUpdatedFlexSkeletonHeaderStructName_FOR_OOT">` entries somewhere in the oot repo (duplicate of `config_oot.xml` in the zapd repo).
Have `config.xml` with `<StructName id="FlexSkeletonHeader" name="MyUpdatedFlexSkeletonHeaderStructName_FOR_MM">` entries somewhere in the mm repo (duplicate of `config_mm.xml` in the zapd repo).
(`config.xml` would be added on any zapd merge following implementing config)

Whenever oot/mm changes a struct name present in `config.xml`, update it in the config too.

When zapd uses a new struct name, it will be added to the oot/mm repo on next zapd merge by editing `config.xml`, and added immediately to zapd's `config_oot.xml`/`config_mm.xml`.

Jenkins (for the zapd repo) will overwrite oot/mm's `config.xml` with `config_oot.xml`/`config_mm.xml` when building zapd to allow development builds to update `config.xml`.

**Comment by AngheloAlf** [comment]
So, the external names would override the internal ones in case they exist? Or it would be mandatory to extern every struct name?

**Comment by Dragorn421** [comment]
I was thinking "externalize" as in "no hardcoded struct name at all in source code"

**Comment by AngheloAlf** [comment]
So, each time a new resource would need to be added to ZAPD both repos would need to add the corresponding entry to their config file without fallback?

**Comment by Dragorn421** [comment]
I guess? I don't see how that would be an issue since ZAPD updates are merged in each repo anyway, just edit whatever needs editing in the config at the same time

**Comment by AngheloAlf** [comment]
Because Jenkins would be mad in this repo if the config file is missing in the other repo.
