### ISSUE TITLE
ZAPD silently allows `Blob` without `Offset`

### ISSUE THREAD

**Issue by Dragorn421** [NEstelami/ZAPD#171]
This may also be true for other things than `Blob`, didn't test it

https://github.com/zeldaret/oot/blob/master/assets/xml/objects/gameplay_field_keep.xml#L58
`<Blob Name="gFieldUnaccounted_00CB30" Size="0x800"/>`

I would expect this to fail on extraction, or at least warn about it (missing `Offset` attribute), but ZAPD says nothing.

The `Name` does end up being used (changing it also changes the extracted .c), so ZAPD must be doing some nice magic to still find the right offset for the data.

Good job ZAPD but I guess this could be messed up by moving nodes around in the xml?
I tried moving the `Blob` without `Offset` up in the file and then it got silently ignored

**Comment by AngheloAlf** [comment]
This has been a "feature" since day one (or at least since I joined). I'm not a huge fan tho

**Comment by Dragorn421** [comment]
So what offset does it default to? This behavior may make sense if the xml was meant to have the data in the same order as the file, but that's not the case in many xmls.

**Comment by AngheloAlf** [comment]
It gets the offset of the last element plus its size.
In your example, it takes the offset of the dlist `gFieldDL_00CA70` (0xCA70) and then it adds the size of that dlist (0xC0).

**Comment by Dragorn421** [comment]
the last element as in,
the element which has the greatest offset yet,
or the last-read element

**Comment by AngheloAlf** [comment]
The last element read. The one just behind it.
