### ISSUE TITLE
ZAPD should use sizeof

### ISSUE THREAD

**Issue by louist103** [NEstelami/ZAPD#183]
Currently ZAPD will extract asset files like this:
```c
Gfx sOtyukaPlatformBottomDL[] = {
    gsSPVertex(&sOtyukaPlatformBottomVtx[0], 4, 0),
    gsSP2Triangles(0, 2, 1, 0, 0, 3, 2, 0),
    gsSPEndDisplayList(),
}; 
```
Assets that are currently in the repo have things like this:
```c
 Gfx sPlatformBottomDList[] = {
    gsSPVertex(sPlatformBottomVerts, ARRAY_COUNT(sPlatformBottomVerts), 0),
    gsSP2Triangles(0, 2, 1, 0, 0, 3, 2, 0),
    gsSPEndDisplayList(),
};
```
Another example of this
```c
CollisionHeader sOtyukaCollision = { 
    { -60, -60, -60 },
    { 60, 0, 60 },
    8,
    sOtyukaCollision_vtx_00002540,
    10,
    sOtyukaCollision_polygons_000024A0,
    sOtyukaCollision_surfaceType_00002490,
    sOtyukaCollision_camDataList_00002488,
    0,
    NULL
}; 
```
Is being extract instead of:
```c
static CollisionHeader sColHeader = {
    { -60, -60, -60 }, { 60, 0, 60 },    ARRAY_COUNT(sVtxList), sVtxList, ARRAY_COUNT(sPolyList),
    sPolyList,         sSurfaceTypeList, sCameraDataList,       0,        NULL,
};
```

**Comment by Dragorn421** [comment]
I think for the vertex buffers it makes more sense to *not* use sizeof / array length since it's quite common to load sub-arrays of the full vertex array into the rsp's vertex buffer

**Comment by fig02** [comment]
agreed, i think it straight up just wont work in many scenarios

**Comment by AngheloAlf** [comment]
I think that's how libgfxd outputs dlists. I don't know if that library allows to change that behaviour.

**Comment by louist103** [comment]
Alright so maybe not for anything GFX related but it should be ok to use for collision right? Or maybe animations of there are any hard codes sizes in there

**Comment by louist103** [comment]
#278
