### ISSUE TITLE
Expose and use defines for texture dimensions

### ISSUE THREAD

**Issue by EllipticEllipsis** [NEstelami/ZAPD#212]
Some files, such as the error messages in MM's `sys_initial_check`, require that the dimensions and filesizes of the textures are used in the code. To be able to do this most coherently,
- ZAPD ought to expose both the texture's dimensions and its size for external use. 
- These could also be used in displaylists that use textures.

This would keep the hardcoding of sizes to a minimum. Exposure will probably be done via a set of defines for each texture, in the asset file's header (or more suitable place in the case of `static` textures), of the form `[...]_WIDTH`, `[...]_HEIGHT`, `[...]_SIZE` If suitable string manipulation is not available or too costly, appending these to the variable name should be sufficient to avoid clashes.

**Comment by NEstelami** [comment]
Resolved in PR #233.
