### ISSUE TITLE
Some inconsistent asset naming (OoT  big key)

### ISSUE THREAD

**Issue by mdtauk** [NEstelami/ZAPD#238]
**big_key**_item_name_ger.ia4.png

**bigkey**_item_name_unused_eng.ia4.png

Also I can't seem to find a "Boss Key" english texture, only

boss_key_item_name_fra.ia4.png

**Comment by Dragorn421** [comment]
The game assets are described in xmls in the game's repositories, ZAPD is only the tool to read these xmls and process the assets. The zapd repo doesn't include assets descriptions

For example the images you're refering to are described in `assets/xml/textures/item_name_static.xml` in the oot repo: https://github.com/zeldaret/oot/blob/master/assets/xml/textures/item_name_static.xml

**Comment by mdtauk** [comment]
So should the XML file be modified?

I also found:
deku_nut_item_name_eng.ia4.png
deku_nut_item_name_fra.ia4.png

**dekunut**_item_name_ger.ia4.png

**Comment by Dragorn421** [comment]
My point was this issue is not related to ZAPD, which this is the repository of
