### ISSUE TITLE
ZAPD silently ignores too-large `NumPaths` values (`Path` resource)

### ISSUE THREAD

**Issue by Dragorn421** [NEstelami/ZAPD#241]
For example in oot's ganon_final.xml, add or replace:
```xml
<Path Name="ganon_final_scenePathList_0001F4" Offset="0x01F4" NumPaths="1000000000"/>
```
The result after extraction is still
```c
Path ganon_final_scenePathList_0001F4[] = {
    { 8, ganon_final_scenePathwayList_000160 },
    { 5, ganon_final_scenePathwayList_000190 },
    { 5, ganon_final_scenePathwayList_0001B0 },
    { 6, ganon_final_scenePathwayList_0001D0 },
};

u8 ganon_final_scene_possiblePadding_000214[] = {
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
};
```
without any warning or error during extraction. Any `NumPaths` over 4 is just like it was 4 (which is indeed the correct amount)

ZAPD should probably at least show a message, similar to when two resources overlap.
There may even be reasons to have a `{ 0, NULL }` entry anyway in the past list, like deleting a path without shifting the table

`NumPaths` below 4 do clamp the size to whatever number (aka "2" will result in two elements in `ganon_final_scenePathList_0001F4`)

**Comment by fig02** [comment]
related to the Path resource, Path should probably be PathList as it contains a list of multiple paths (pointed out by roman in a recent pr)

**Comment by NEstelami** [comment]
> For example in oot's ganon_final.xml, add or replace:
> 
> ```
> <Path Name="ganon_final_scenePathList_0001F4" Offset="0x01F4" NumPaths="1000000000"/>
> ```
> 
> The result after extraction is still
> 
> ```c
> Path ganon_final_scenePathList_0001F4[] = {
>     { 8, ganon_final_scenePathwayList_000160 },
>     { 5, ganon_final_scenePathwayList_000190 },
>     { 5, ganon_final_scenePathwayList_0001B0 },
>     { 6, ganon_final_scenePathwayList_0001D0 },
> };
> 
> u8 ganon_final_scene_possiblePadding_000214[] = {
>     0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
> };
> ```
> 
> without any warning or error during extraction. Any `NumPaths` over 4 is just like it was 4 (which is indeed the correct amount)
> 
> ZAPD should probably at least show a message, similar to when two resources overlap. There may even be reasons to have a `{ 0, NULL }` entry anyway in the past list, like deleting a path without shifting the table
> 
> `NumPaths` below 4 do clamp the size to whatever number (aka "2" will result in two elements in `ganon_final_scenePathList_0001F4`)

It seems ZAPD no longer does this. I tried setting numPaths to `1000000000` and it crashed.

**Comment by NEstelami** [comment]
`PathList` node added in PR #280.
