### ISSUE TITLE
Bug in Vtx data extraction

### ISSUE THREAD

**Issue by Dragorn421** [NEstelami/ZAPD#253]
From https://github.com/zeldaret/oot/pull/1250

For example: OoT, `assets/scenes/test_levels/sasatest/sasatest_room_0.c`

`gsSPVertex(&sasatest_room_0Vtx_000370[28], 8, 1)` uses vertices 28 to 35 (inclusive) from `sasatest_room_0Vtx_000370`
but the vertex array as currently extracted is only of length `33`
(for example vertex 33 is extracted as "unaccounted", `sasatest_room_0_unaccounted_000580`)

**Comment by NEstelami** [comment]
Resolved with PR #281.
