### ISSUE TITLE
The list of cutscene command ids that are `CS_NPC_ACTION_LIST` is incomplete or wrong

### ISSUE THREAD

**Issue by Dragorn421** [NEstelami/ZAPD#256]
`CS_NPC_ACTION_LIST` can use different cs cmd ids, it seems that ZAPD's list of those cmd ids is incomplete/wrong, as some are extracted as `CS_UNK_DATA_LIST` instead

The example Fig noticed:
`gTempleOfTimeFirstAdultCs` in `assets/scenes/indoors/tokinoma/tokinoma_scene.c`
has `CS_UNK_DATA_LIST(0x4A, 2),`
but 0x4A = 74 is a "real"/implemented command id:
`case 74:` in https://github.com/zeldaret/oot/blob/9647f50451f26fa8b96653bf792f86c6148f6d12/src/code/z_demo.c#L1728
So this should be a `CS_NPC_ACTION_LIST`

Idk if there are other occurrences

**Comment by NEstelami** [comment]
Resolved with PR #282.
