### ISSUE TITLE
ZBackground.cpp uses SCREEN_WIDTH/SCREEN_HEIGHT to set prerendered background dimensions

### ISSUE THREAD

**Issue by mzxrules** [NEstelami/ZAPD#272]
I tried bringing this up in discord but it didn't generate any conversation, so I'll make a formal issue here.

Was considering renaming `SCREEN_WIDTH`/`SCREEN_HEIGHT` when I noticed ZAPD hardcodes prerendered backgrounds to use these constants; afaik there is no reason to tie the decompressed jpeg size to these constants since changing `SCREEN_WIDTH`/`SCREEN_HEIGHT` won't change the dimensions of the background image.

**Comment by NEstelami** [comment]
Resolved with PR #278.
