### ISSUE TITLE
genbuildinfo.py fails if the source is not inside a git repo

### ISSUE THREAD

**Issue by ethteck** [NEstelami/ZAPD#276]
<img width="240" alt="image" src="https://user-images.githubusercontent.com/2985314/234757522-fe5a113c-b7ea-4679-b3c8-54e25854de51.png">
https://discord.com/channels/688807550715560050/688851337085190255/1097789745532252260

I think we can just choose another label if the git command fails. Also we may wanna use a python git module instead of invoking it with `subprocess`

**Comment by ethteck** [comment]
actually subprocess is less dependency-heavy so yeah nevermind on that probably

**Comment by NEstelami** [comment]
Resolved with PR #277.
