### ISSUE TITLE
Building ZAPD on cygwin

### ISSUE THREAD

**Issue by Dragorn421** [NEstelami/ZAPD#304]
From https://github.com/zeldaret/oot/issues/1510

ZAPD checks "posix" with checking for the unistd.h header:
https://github.com/NEstelami/ZAPD/blob/c7dd81e67783a93e728e5662dfe0c8732d79ce59/ZAPD/CrashHandler.cpp#L4-L8

However not all the headers included under HAS_POSIX==1 are posix. At least ~~dlfcn.h~~ and execinfo.h aren't,and are gnu extensions

so has_posix is misnamed,
and also it turns out cygwin doesn't have some headers (execinfo.h, see linked issue)
this prevents building on cygwin

**Comment by louist103** [comment]
The `has_posix` name is fine as the headers are expected to be there on any build system that is POSIX compliant. (https://www.open-std.org/jtc1/sc22/open/n4217.pdf page 205, and 412). I will agree though that we need a better way to test for the proper headers.

**Comment by Dragorn421** [comment]
My bad dlfcn.h is posix (in linux it also contains gnu extensions though),
but execinfo.h isn't afaict
