### ISSUE TITLE
Accounting for alignment when generating C files

### ISSUE THREAD

**Issue by Roman971** [NEstelami/ZAPD#32]
Currently, ZAPD generates many small `unaccounted` arrays of 0s. Most of these could be omitted when they are just padding for end of file alignment (to 0x10 bytes) or long alignment (to 8 bytes) when the next element is a texture (`u64[]`), vertices (`Vtx[]`) or display lists (`Gfx[]`).

**Comment by NEstelami** [comment]
ZAPD has support for alignment and padding, and it used to be used a lot more. I found that with rooms and scenes in particular, the alignment/padding of structs was inconsistent across files, so I had to rely more on `unaccounted`.

**Comment by AngheloAlf** [comment]
I think this one should be addressed already too
