### ISSUE TITLE
Fix handling of CI textures

### ISSUE THREAD

**Issue by Zelllll** [NEstelami/ZAPD#44]
Currently CI4 textures do no extract correctly, however this presents an opportunity to improve the handling of CI textures as a whole.
CI textures should be changed to use .tga since its the only format that can handle palettes while also having an alpha channel. This way the images could actually look as intended as well, rather than just being grayscale.

**Comment by Zelllll** [comment]
It turns out that we can actually likely continue to use png's like we do already, because png supports indexed images, we should look into this

**Comment by NEstelami** [comment]
STBI doesn't appear to handle writing palettized images, so should we go this route I am going to need to look into another library or into modifying STBI as needed.

**Comment by Kenix3** [comment]
This has been fixed.
