### ISSUE TITLE
ZAP allocates a lot of memory and resources that are never freed.

### ISSUE THREAD

**Issue by Kenix3** [NEstelami/ZAPD#52]
This is not meant to be a 100% exhaustive list.
- [x] XML handle may not be closed.
- [ ] File handles may not be closed.
- [x] Strings that are not stack variables need to be freed. Some come from XML, and it may handle freeing of those. We need to consult documentation.
- [x] ZFile.resources needs to free and destroy the ZResource on ZFile destructor.
- [x] ZFiles need to be destroyed after the XML file is done being processed. They are allocated memory in a few places, but never freed.
- [x] ZCollision allocates VertexEntry classes into the vertices vector and never frees them.
- [x] ZCollision allocates PolygonEntry classes into the polygons vector and never frees them.
- [x] ZCollision allocates a CameraDataList and never frees it.
- [x] ZCollision allocates WaterBoxHeader classes into the waterBoxes vector and never frees them.
- [x] ZCutscene allocates commands into the commands vector and never frees them.
- [ ] ZDisplayList allocates ZDisplayLists into the otherDLists vector and never frees them.
- [x] File.ReadAllBytes allocates a char array that is never freed.
- [x] File.ReadAllText allocates a char array that is never freed.
- [x] SetListActor allocates ActorSpawnEntry to the actors vector and never frees them.
- [x] SetCutscenes allocates ZCutscene to the cutscenes vector and never frees them.
- [x] SetEntranceList allocates EntranceEntry to the entrances vector and never frees them.
- [x] SetLightSettings allocates LightingSettings to the settings vectors and never frees them.
- [x] SetMesh allocates MeshHeader and other objects, but never frees them.
- [x] SetPathways allocates PathwayEntry to the pathways vector and never frees them.
- [x] SetRoomList allocates RoomEntry to the rooms vector and never frees them.
- [x] SetStartPositionList allocates ActorSpawnEntry to the actors vector and never frees them.
- [x] SetTransitionActorList allocates TransitionActorEntry to the transitionActors vector and never frees them.
- [ ] ZRoom.ExtractFromXML allocates multiple objects and never frees them.
- [x] ZRoom allocates room commands to the commandList vector and never frees them.
- [x] ZLimbStandard.FromRawData allocates a ZLimbStandard that is never freed or added to the ZResource list in a ZFile.
- [x] ZLimbLOD::FromRawData allocates a ZLimbLOD that is never freed or added to the ZResource list in a ZFile.
- [ ] There are ZDisplayList allocations throughout the code that are never freed or added to the ZResource list in a ZFile.
- [ ] Final audit of all opened file handles, xml handles, and all uses of the "new" operator for a later delete.

**Comment by NEstelami** [comment]
Anything in particular stand out to you? I know ZTexture and ZOverlay make allocations, but they also free them on destroy. I guess for Rooms/Scenes their commands need to be freed once all is done.

**Comment by Kenix3** [comment]
> 
> 
> Anything in particular stand out to you? I know ZTexture and ZOverlay make allocations, but they also free them on destroy. I guess for Rooms/Scenes their commands need to be freed once all is done.

As far as what specifically comes to mind. This is not meant to be a 100% exhaustive list.
- XML handle may not be closed.
- File handles may not be closed.
- Strings that are not stack variables need to be freed. Some come from XML, and it may handle freeing of those. We need to consult documentation.
- ZFile.resources needs to free and destroy the ZResource on ZFile destructor.
- ZFiles need to be destroyed after the XML file is done being processed. They are allocated memory in a few places, but never freed.
- ZCollision allocates VertexEntry classes into the vertices vector and never frees them.
- ZCollision allocates PolygonEntry classes into the polygons vector and never frees them.
- ZCollision allocates a CameraDataList and never frees it.
- ZCollision allocates WaterBoxHeader classes into the waterBoxes vector and never frees them.
- ZCutscene allocates commands into the commands vector and never frees them.
- ZDisplayList allocates ZDisplayLists into the otherDLists vector and never frees them.
- File.ReadAllBytes allocates a char array that is never freed.
- File.ReadAllText allocates a char array that is never freed.
- SetListActor allocates ActorSpawnEntry to the actors vector and never frees them.
- SetCutscenes allocates ZCutscene to the cutscenes vector and never frees them.
- SetEntranceList allocates EntranceEntry to the entrances vector and never frees them.
- SetLightSettings allocates LightingSettings to the settings vectors and never frees them.
- SetMesh allocates MeshHeader and other objects, but never frees them.
- SetPathways allocates PathwayEntry to the pathways vector and never frees them.
- SetRoomList allocates RoomEntry to the rooms vector and never frees them.
- SetStartPositionList allocates ActorSpawnEntry to the actors vector and never frees them.
- SetTransitionActorList allocates TransitionActorEntry to the transitionActors vector and never frees them.
- ZRoom.ExtractFromXML allocates multiple objects and never frees them.
- ZRoom allocates room commands to the commandList vector and never frees them.
- ZLimbStandard.FromRawData allocates a ZLimbStandard that is never freed or added to the ZResource list in a ZFile.
- ZLimbLOD::FromRawData allocates a ZLimbLOD  that is never freed or added to the ZResource list in a ZFile.
- There are ZDisplayList allocations throughout the code that are never freed or added to the ZResource list in a ZFile.
