### ISSUE TITLE
Unhandled OP codes

### ISSUE THREAD

**Issue by louist103** [NEstelami/ZAPD#86]
The following OP codes are in yet supported:
    // Opcode 0xE4 unimplemented!
    // Opcode 0xE4 unimplemented!
    // Opcode 0xF1 unimplemented!

XML to recreate can be found here:
https://github.com/louist103/oot/blob/ObjectDecomp/assets/xml/objects/gameplay_field_keep.xml
commit e659d71

**Comment by AngheloAlf** [comment]
#84 fixes this issue.
